main: fr.pederobien.minecraft.border.BorderPlugin
name: minecraft-border
version: 1.0_MC_1.16.5-SNAPSHOT
api-version: 1.16.5
depend: [minecraft-platform]

commands:
  border:
    description: This command is used to manipulate a border configurations.
    permission: PlateformPlugin.permission