main: fr.pederobien.minecraft.border.BorderPlugin
name: minecraft-border
version: 1.0_MC_1.13.2-SNAPSHOT
api-version: 1.13
depend: [minecraft-game-platform]

commands:
  border:
    description: This command is used to manipulate a border configurations.
    permission: PlateformPlugin.permission